import { countries } from "../data/countries.js"; import { researchTopics as topics } from "../data/research/topics.js"; import { forecasts } from "../data/forecasts.js"; import { sources } from "../data/research/sources.js"; import { claims } from "../data/research/claims.js"; import { events } from "../data/research/events.js";
const $=s=>document.querySelector(s); const country=$('#country-filter'),domain=$('#domain-filter'),search=$('#search'),grid=$('#topic-grid'),count=$('#result-count'),dialog=$('#topic-dialog');
const statuses=["unassessed","resolved","partially_resolved","active","deeply_unresolved","dormant"];
country.innerHTML=countries.filter(c=>c.enabled).map(c=>`<option value="${c.id}">${c.name}</option>`).join(''); domain.innerHTML='<option value="all">All domains</option>'+countries[0].domains.map(x=>`<option>${x}</option>`).join(''); $('#status-filters').innerHTML=statuses.map(s=>`<label><input type="checkbox" value="${s}" checked> ${s}</label>`).join('');
const displayStatus=t=>t.assessment_status==='unassessed'?'unassessed':t.status;
function filtered(){const active=[...document.querySelectorAll('#status-filters input:checked')].map(i=>i.value), q=search.value.toLowerCase().trim();return topics.filter(t=>t.country_id===country.value&&(domain.value==='all'||t.domain===domain.value)&&active.includes(displayStatus(t))&&`${t.title} ${t.subtopics.join(' ')} ${t.domain}`.toLowerCase().includes(q));}
function card(t){return `<button class="topic-card" data-id="${t.id}"><span class="tag status-${displayStatus(t)}">${displayStatus(t).replace('_',' ')}</span><h3>${t.title}</h3><p>${t.domain} · ${t.subtopics[0]}</p><div class="card-meta"><span class="tag">Priority unassessed</span><span class="tag">Baseline</span></div></button>`}
function render(){const list=filtered();grid.innerHTML=list.map(card).join('')||'<p>No topics match these filters.</p>';count.textContent=`${list.length} topic${list.length===1?'':'s'}`;grid.querySelectorAll('[data-id]').forEach(b=>b.addEventListener('click',()=>open(b.dataset.id)));signals();}
function signals(){const visible=topics.filter(t=>t.country_id===country.value); const top=(key)=>visible.reduce((a,b)=>a[key]>b[key]?a:b); $('#most-active').textContent=top('momentum').title;$('#most-unresolved').textContent=top('uncertainty').title;$('#likely-change').textContent=top('momentum').title;}
function open(id){const t=topics.find(x=>x.id===id), topicSources=t.sources.map(id=>sources.find(s=>s.id===id)).filter(Boolean), topicClaims=t.claims.map(id=>claims.find(c=>c.id===id)).filter(Boolean), topicEvents=t.events.map(id=>events.find(e=>e.id===id)).filter(Boolean); const sourceList=topicSources.length?`<ul class="evidence-list">${topicSources.map(s=>`<li><a href="${s.url}" target="_blank" rel="noreferrer">${s.title}</a><span>${s.publisher}${s.published_at?` · ${s.published_at}`:''}</span></li>`).join('')}</ul>`:'<p>No sources have been linked yet.</p>'; const claimList=topicClaims.length?`<ul class="evidence-list">${topicClaims.map(c=>`<li><strong>${c.claim_type}</strong><span>${c.text}</span></li>`).join('')}</ul>`:'<p>No claims have been published yet.</p>'; const eventList=topicEvents.length?`<ul class="evidence-list">${topicEvents.map(e=>`<li><strong>${e.date} · ${e.materiality}</strong><span>${e.title}</span></li>`).join('')}</ul>`:'<p>No events have been recorded yet.</p>'; $('#dialog-content').innerHTML=`<div class="dialog-body"><p class="eyebrow">${t.domain} · ${t.subtopics[0]} · ${t.assessment_status==='unassessed'?'unassessed editorial baseline':'provisional assessment'}</p><h2>${t.title}</h2><div class="detail-grid"><article><h3>Assessment status</h3><p>${t.assessment_status==='unassessed'?'This topic has not yet undergone evidence-based assessment. It is not classified as deeply unresolved.':'This is a provisional evidence-based assessment and remains incomplete.'}</p></article><article><h3>Forecast</h3><p>No forecast published. Forecasts require dated scenarios, confidence, rationale, and evidence.</p></article><article><h3>Assessment dimensions</h3><p>Importance ${t.importance ?? 'unassessed'} · Uncertainty ${t.uncertainty ?? 'unassessed'} · Institutional disagreement ${t.institutional_disagreement ?? 'unassessed'} · Momentum ${t.momentum ?? 'unassessed'}</p></article><article><h3>Last assessed</h3><p>${t.last_assessed ?? 'Not yet assessed'}</p></article></div><section class="evidence-section"><h3>Sources</h3>${sourceList}<h3>Claims</h3>${claimList}<h3>Events</h3>${eventList}</section><div class="definition"><h3>Definition of resolved</h3><p>${t.definition_of_resolved}</p></div></div>`;dialog.showModal();}
[country,domain,search,document.querySelector('#status-filters')].forEach(el=>el.addEventListener('input',render));$('.dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});render();
