import { countries } from "../data/countries.js"; import { researchTopics as topics } from "../data/research/topics.js"; import { forecasts } from "../data/forecasts.js"; import { sources } from "../data/research/sources.js"; import { claims } from "../data/research/claims.js"; import { events } from "../data/research/events.js";
import { assessmentNotes } from "../data/research/assessment_notes.js"; import { positions } from "../data/research/positions.js"; import { forecasts as reviewedForecasts } from "../data/research/forecasts.js";
const $=s=>document.querySelector(s); const country=$('#country-filter'),domain=$('#domain-filter'),search=$('#search'),grid=$('#topic-grid'),count=$('#result-count'),dialog=$('#topic-dialog');
const statuses=["unassessed","resolved","partially_resolved","active","deeply_unresolved","dormant"];
country.innerHTML=countries.filter(c=>c.enabled).map(c=>`<option value="${c.id}">${c.name}</option>`).join(''); domain.innerHTML='<option value="all">All domains</option>'+countries[0].domains.map(x=>`<option>${x}</option>`).join(''); $('#status-filters').innerHTML=statuses.map(s=>`<label><input type="checkbox" value="${s}" checked> ${s}</label>`).join('');
const displayStatus=t=>t.assessment_status==='unassessed'?'unassessed':t.status;
function priority(t){return [t.importance,t.uncertainty,t.momentum].every(Number.isFinite)?Math.round(t.importance*t.uncertainty*t.momentum/10000):null;}\nfunction filtered(){const active=[...document.querySelectorAll('#status-filters input:checked')].map(i=>i.value), q=search.value.toLowerCase().trim();return topics.filter(t=>t.country_id===country.value&&(domain.value==='all'||t.domain===domain.value)&&active.includes(displayStatus(t))&&`${t.title} ${t.subtopics.join(' ')} ${t.domain}`.toLowerCase().includes(q)).sort((a,b)=>(priority(b)??-1)-(priority(a)??-1)||a.title.localeCompare(b.title));}
function card(t){const priorityLabel=priority(t) ?? 'unassessed';return `<button class="topic-card" data-id="${t.id}"><span class="tag status-${displayStatus(t)}">${displayStatus(t).replace('_',' ')}</span><h3>${t.title}</h3><p>${t.domain} · ${t.subtopics[0]}</p><div class="card-meta"><span class="tag">Priority ${priorityLabel}</span><span class="tag">${t.assessment_status==='researched'?'Reviewed':'Baseline'}</span></div></button>`}
function render(){const list=filtered();grid.innerHTML=list.map(card).join('')||'<p>No topics match these filters.</p>';count.textContent=`${list.length} topic${list.length===1?'':'s'}`;grid.querySelectorAll('[data-id]').forEach(b=>b.addEventListener('click',()=>open(b.dataset.id)));signals();}
function signals(){const visible=topics.filter(t=>t.country_id===country.value); const top=(key)=>visible.reduce((a,b)=>a[key]>b[key]?a:b); $('#most-active').textContent=top('momentum').title;$('#most-unresolved').textContent=top('uncertainty').title;$('#likely-change').textContent=top('momentum').title;}
function open(id){const t=topics.find(x=>x.id===id), topicSources=t.sources.map(id=>sources.find(s=>s.id===id)).filter(Boolean), topicClaims=t.claims.map(id=>claims.find(c=>c.id===id)).filter(Boolean), topicEvents=t.events.map(id=>events.find(e=>e.id===id)).filter(Boolean), topicPositions=positions.filter(p=>p.topic_id===id), forecast=reviewedForecasts.find(f=>f.topic_id===id), notes=assessmentNotes[id]?.dimensions ?? {}; const sourceList=topicSources.length?`<ul class="evidence-list">${topicSources.map(s=>`<li><a href="${s.url}" target="_blank" rel="noreferrer">${s.title}</a><span>${s.publisher}${s.published_at?` · ${s.published_at}`:''}</span></li>`).join('')}</ul>`:'<p>No sources have been linked yet.</p>'; const claimList=topicClaims.length?`<ul class="evidence-list">${topicClaims.map(c=>`<li><strong>${c.claim_type}</strong><span>${c.text}</span></li>`).join('')}</ul>`:'<p>No claims have been published yet.</p>'; const eventList=topicEvents.length?`<ul class="evidence-list">${topicEvents.map(e=>`<li><strong>${e.date} · ${e.materiality}</strong><span>${e.title}</span></li>`).join('')}</ul>`:'<p>No events have been recorded yet.</p>'; const positionList=topicPositions.length?`<ul class="evidence-list">${topicPositions.map(p=>`<li><strong>${p.actor}</strong><span>${p.position}</span></li>`).join('')}</ul>`:'<p>No attributed positions have been recorded yet.</p>'; const dimensionList=Object.entries(notes).map(([name,item])=>`<li><strong>${name.replaceAll('_',' ')}</strong><span>${item.value ?? 'unassessed'} — ${item.basis}</span></li>`).join(''); const forecastText=forecast?`${forecast.base_case} Probabilities: ${Object.entries(forecast.probabilities).map(([k,v])=>`${k} ${Math.round(v*100)}%`).join(', ')} Confidence: ${forecast.confidence}/100. Rationale: ${forecast.rationale}`:'No forecast published.'; $('#dialog-content').innerHTML=`<div class="dialog-body"><p class="eyebrow">${t.domain} · ${t.subtopics[0]} · ${t.assessment_status==='unassessed'?'unassessed editorial baseline':'reviewed assessment'}</p><h2>${t.title}</h2><div class="detail-grid"><article><h3>Assessment status</h3><p>${t.assessment_status==='unassessed'?'This topic has not yet undergone evidence-based assessment. It is not classified as deeply unresolved.':'Reviewed assessment; scores are editorial judgments grounded in the linked evidence.'}</p></article><article><h3>Forecast</h3><p>${forecastText}</p></article><article><h3>Assessment dimensions</h3><ul class="evidence-list">${dimensionList}</ul></article><article><h3>Last assessed</h3><p>${t.last_assessed ?? 'Not yet assessed'}</p></article></div><section class="evidence-section"><h3>Sources</h3>${sourceList}<h3>Claims</h3>${claimList}<h3>Events</h3>${eventList}<h3>Ongoing discussions</h3>${positionList}</section><div class="definition"><h3>Definition of resolved</h3><p>${t.definition_of_resolved}</p></div></div>`;dialog.showModal();}
[country,domain,search,document.querySelector('#status-filters')].forEach(el=>el.addEventListener('input',render));$('.dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});render();
