import { countries } from "../data/countries.js"; import { researchTopics as topics } from "../data/research/topics.js"; import { forecasts } from "../data/forecasts.js";
const $=s=>document.querySelector(s); const country=$('#country-filter'),domain=$('#domain-filter'),search=$('#search'),grid=$('#topic-grid'),count=$('#result-count'),dialog=$('#topic-dialog');
const statuses=["resolved","partially_resolved","active","deeply_unresolved","dormant"];
country.innerHTML=countries.filter(c=>c.enabled).map(c=>`<option value="${c.id}">${c.name}</option>`).join(''); domain.innerHTML='<option value="all">All domains</option>'+countries[0].domains.map(x=>`<option>${x}</option>`).join(''); $('#status-filters').innerHTML=statuses.map(s=>`<label><input type="checkbox" value="${s}" checked> ${s}</label>`).join('');
function filtered(){const active=[...document.querySelectorAll('#status-filters input:checked')].map(i=>i.value), q=search.value.toLowerCase().trim();return topics.filter(t=>t.country_id===country.value&&(domain.value==='all'||t.domain===domain.value)&&active.includes(t.status)&&`${t.title} ${t.subtopics.join(' ')} ${t.domain}`.toLowerCase().includes(q));}
function card(t){return `<button class="topic-card" data-id="${t.id}"><span class="tag status-${t.status}">${t.status.replace('_',' ')}</span><h3>${t.title}</h3><p>${t.domain} · ${t.subtopics[0]}</p><div class="card-meta"><span class="tag">Priority ${Math.round(t.importance*t.uncertainty*t.momentum/10000)}</span><span class="tag">Baseline</span></div></button>`}
function render(){const list=filtered();grid.innerHTML=list.map(card).join('')||'<p>No topics match these filters.</p>';count.textContent=`${list.length} topic${list.length===1?'':'s'}`;grid.querySelectorAll('[data-id]').forEach(b=>b.addEventListener('click',()=>open(b.dataset.id)));signals();}
function signals(){const visible=topics.filter(t=>t.country_id===country.value); const top=(key)=>visible.reduce((a,b)=>a[key]>b[key]?a:b); $('#most-active').textContent=top('momentum').title;$('#most-unresolved').textContent=top('uncertainty').title;$('#likely-change').textContent=top('momentum').title;}
function open(id){const t=topics.find(x=>x.id===id);$('#dialog-content').innerHTML=`<div class="dialog-body"><p class="eyebrow">${t.domain} · ${t.subtopics[0]} · editorial baseline</p><h2>${t.title}</h2><div class="detail-grid"><article><h3>Facts</h3><p>No factual claims have been published until evidence records are added.</p></article><article><h3>Forecast</h3><p>No forecast published. Forecasts require dated scenarios, confidence, rationale, and evidence.</p></article><article><h3>Assessment</h3><p>Importance ${t.importance} · Uncertainty ${t.uncertainty} · Institutional disagreement ${t.institutional_disagreement} · Momentum ${t.momentum}</p></article><article><h3>Last assessed</h3><p>${t.last_assessed ?? 'Editorial baseline — not yet assessed'}</p></article></div><div class="definition"><h3>Definition of resolved</h3><p>${t.definition_of_resolved}</p></div></div>`;dialog.showModal();}
[country,domain,search,document.querySelector('#status-filters')].forEach(el=>el.addEventListener('input',render));$('.dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});render();
