const list=document.querySelector("#review-list"),count=document.querySelector("#review-count"),submitButton=document.querySelector("#submit-review"),exportButton=document.querySelector("#export-review");
let payload={candidates:[],errors:[]};
const decisions=JSON.parse(localStorage.getItem("unresolved-review-decisions")||"{}");
function esc(value){return String(value??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));}
function decisionFor(row){return decisions[row.id]||null;}
function visibleRows(){return (payload.candidates||[]).filter(row=>!decisionFor(row));}
function automatedReviewFor(row){return row.automated_review_comment||{assessment:"needs_context",label:"needs context",score:null,comment:"No automated triage note was stored for this candidate. Review the source and topic context manually.",basis:["legacy candidate record without an automated assessment"],method:"deterministic editorial triage; not an AI or publication decision"};}
function render(){const rows=visibleRows();count.textContent=rows.length?rows.length+" candidate update"+(rows.length===1?"":"s")+" · decisions saved locally":"No candidate updates";list.innerHTML=rows.length?rows.map(row=>{const review=automatedReviewFor(row),score=Number.isFinite(review.score)?` · ${review.score}/100`:"";return `<article class="review-card" data-id="${esc(row.id)}"><div class="review-meta"><span>${esc(row.topic_id)}</span><span>${esc(row.published_at||"undated")}</span><span>${esc(row.source_id)}</span></div><h2>${esc(row.title)}</h2><p>${esc(row.summary||"No excerpt supplied.")}</p><p><a href="${esc(row.url)}" target="_blank" rel="noreferrer">Open source</a></p><section class="automated-review-comment" aria-label="Automated pre-review assessment"><div class="automated-review-heading"><strong>Automated pre-review assessment</strong><span class="review-assessment review-assessment-${esc(review.assessment)}">${esc(review.label||review.assessment)}${score}</span></div><p>${esc(review.comment)}</p><p class="review-basis"><strong>Basis:</strong> ${esc((review.basis||[]).join("; ")||"No basis recorded.")}</p><small>${esc(review.method||"Deterministic editorial triage; not a publication decision.")}</small></section><div class="review-actions"><button class="approve" data-decision="approved">Approve for editorial processing</button><button class="reject" data-decision="rejected">Reject candidate</button></div></article>`}).join(""):`<div class="empty">No discovered candidates are waiting. The next scheduled discovery run will populate this queue when configured feeds change.</div>`;list.querySelectorAll("button").forEach(button=>button.addEventListener("click",()=>{const card=button.closest(".review-card"),id=card.dataset.id;decisions[id]=button.dataset.decision;localStorage.setItem("unresolved-review-decisions",JSON.stringify(decisions));render();}));}
function submitApproved(){const rows=(payload.candidates||[]).filter(row=>decisions[row.id]==="approved"||decisions[row.id]==="rejected");const approvedCount=rows.filter(row=>decisions[row.id]==="approved").length;if(!rows.length){window.alert("Approve or reject at least one candidate before submitting.");return;}const submitted={submitted_at:new Date().toISOString(),decisions:Object.fromEntries(rows.map(row=>[row.id,decisions[row.id]])),approved_count:approvedCount};const body=`<!-- unresolved-index-review:v1
${JSON.stringify(submitted)}
-->

This review request was submitted from the Unresolved Index review page. The workflow will validate the candidates and open an implementation PR.`;const url="https://github.com/Irneh0001/the-unresolved-index/issues/new?title="+encodeURIComponent("Apply approved research updates")+"&body="+encodeURIComponent(body);window.open(url,"_blank","noopener");}
submitButton.addEventListener("click",submitApproved);
exportButton.addEventListener("click",()=>{const blob=new Blob([JSON.stringify({exported_at:new Date().toISOString(),decisions},null,2)],{type:"application/json"});const link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download="unresolved-index-review-decisions.json";link.click();URL.revokeObjectURL(link.href);});
Promise.all([fetch("data/research/candidates.generated.json").then(response=>response.ok?response.json():{candidates:[],errors:[]}),fetch("data/research/review-decisions/unresolved-index-review-decisions.json").then(response=>response.ok?response.json():{decisions:{}})]).then(([data,review])=>{payload=data;Object.assign(decisions,review.decisions||{});render();}).catch(()=>{payload={candidates:[],errors:["Candidate queue unavailable"]};render();});
