const list=document.querySelector("#review-list"),count=document.querySelector("#review-count"),exportButton=document.querySelector("#export-review");
let payload={candidates:[],errors:[]};
const decisions=JSON.parse(localStorage.getItem("unresolved-review-decisions")||"{}");
function esc(value){return String(value??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));}
function decisionFor(row){if(decisions[row.id])return decisions[row.id];const prefix=`candidate-${row.source_id}-${row.published_at||"undated"}-`;const legacy=Object.keys(decisions).find(id=>id.startsWith(prefix));return legacy?decisions[legacy]:null;}
function visibleRows(){return (payload.candidates||[]).filter(row=>!decisionFor(row));}
function render(){const rows=visibleRows();count.textContent=rows.length?rows.length+" candidate update"+(rows.length===1?"":"s")+" · decisions saved locally":"No candidate updates";list.innerHTML=rows.length?rows.map(row=>`<article class="review-card" data-id="${esc(row.id)}"><div class="review-meta"><span>${esc(row.topic_id)}</span><span>${esc(row.published_at||"undated")}</span><span>${esc(row.source_id)}</span></div><h2>${esc(row.title)}</h2><p>${esc(row.summary||"No excerpt supplied.")}</p><p><a href="${esc(row.url)}" target="_blank" rel="noreferrer">Open source</a></p><div class="review-actions"><button class="approve" data-decision="approved">Approve for editorial processing</button><button class="reject" data-decision="rejected">Reject candidate</button></div></article>`).join(""):`<div class="empty">No discovered candidates are waiting. The next scheduled discovery run will populate this queue when configured feeds change.</div>`;list.querySelectorAll("button").forEach(button=>button.addEventListener("click",()=>{const card=button.closest(".review-card"),id=card.dataset.id;decisions[id]=button.dataset.decision;localStorage.setItem("unresolved-review-decisions",JSON.stringify(decisions));render();}));}
exportButton.addEventListener("click",()=>{const blob=new Blob([JSON.stringify({exported_at:new Date().toISOString(),decisions},null,2)],{type:"application/json"});const link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download="unresolved-index-review-decisions.json";link.click();URL.revokeObjectURL(link.href);});
Promise.all([fetch("data/research/candidates.generated.json").then(response=>response.ok?response.json():{candidates:[],errors:[]}),fetch("data/research/review-decisions/unresolved-index-review-decisions.json").then(response=>response.ok?response.json():{decisions:{}})]).then(([data,review])=>{payload=data;Object.assign(decisions,review.decisions||{});render();}).catch(()=>{payload={candidates:[],errors:["Candidate queue unavailable"]};render();});
